name: Docker Image CI
on:
  push:
    paths:
        - ".devcontainer/Dockerfile"
        - ".github/**"
    branches: [main]
  pull_request:
    paths:
        - ".devcontainer/Dockerfile"
        - ".github/**"
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        ghc: ["9.0.2"]
        stack: ["2.7.5"]
        resolver: ["lts-19.16"]
        cabal: ["3.6.2.0"]
        hls: ["1.7.0.0"]
    steps:
      -
        name: Get current date
        id: date
        run: echo "::set-output name=now::$(date +s)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:.devcontainer"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/haskelldevenv:${{ matrix.ghc }}-${{ matrix.resolver }}-${{ matrix.resolver }}-${{ steps.date.outputs.now }}
          build-args: |
            GHC_VERSION=${{ matrix.ghc }}
            STACK_RESOLVER=${{ matrix.resolver }}
            STACK_VERSION=${{ matrix.stack }}
            CABAL_VERSION=${{ matrix.cabal }}
            HLS_VERSION=${{ matrix.hls }}
